app:
  name: 'tgmai'
  version: '0.1.4.88'

tg:
  apitoken: "6684907037:AAHSDb2JAlcLDiAacbAMUSQAKbMFHYOtCMk"

logger:
  log_level: 'debug'
  rollbar_env: 'tgmai'

postgres:
  username: "maidtp"
  password: "maidtp"
  host: "localhost"
  port: "5432"
  name: "maidtp"
  pool_max: 10
